export const data = [
  {
    id: 1,
    image: require('../assets/account.png'),
    name: 'Tanmay bhat',
    points: '3,144,203',
    credits: 12,
  },
  {
    id: 2,
    image: require('../assets/account.png'),
    name: 'Mostly sane',
    points: '3,144,203',
    credits: 12,
  },
  {
    id: 3,
    image: require('../assets/account.png'),
    name: 'BB ki vines',
    points: '3,144,203',
    credits: 12,
  },
  {
    id: 4,
    image: require('../assets/account.png'),
    name: 'carryMinati',
    points: '3,144,203',
    credits: 12,
  },
  {
    id: 5,
    image: require('../assets/account.png'),
    name: 'Ashish chancalani',
    points: '3,144,203',
    credits: 12,
  },
  {
    id: 6,
    image: require('../assets/account.png'),
    name: 'Round2Hell',
    points: '3,144,203',
    credits: 12,
  },
  {
    id: 7,
    image: require('../assets/account.png'),
    name: 'Technical guruji',
    points: '3,144,203',
    credits: 12,
  },
  {
    id: 8,
    image: require('../assets/account.png'),
    name: 'Mythpath',
    points: '3,144,203',
    credits: 12,
  },
  {
    id: 9,
    image: require('../assets/account.png'),
    name: 'Amit Bhadana',
    points: '3,144,203',
    credits: 12,
  },
  {
    id: 10,
    image: require('../assets/account.png'),
    name: 'Mr. xyz',
    points: '3,144,203',
    credits: 12,
  },
];
